### PR TITLE
- Generate the repos config file in sorted order

### PR DESCRIPTION
**Pull request by rjschwei**
+ This allows us to more easily diff the generated file to existing
    configurations to better identify changes.

### CODE REVIEW

**Comment by ikapelyukhin** [comment]
It's a really weird data structure anyway: `[ { "123": { "repo_path": "..." } }, ... ]`.

Perhaps it's a good idea to make it into something more sensible, like `[ { "repo_id": "123",  "repo_path": "..." }, ... ]` or even `{ "123": { "repo_path": "..." }, ... }` while we are at it.

**Comment by rjschwei** [comment]
> It's a really weird data structure anyway: `[ { "123": { "repo_path": "..." } }, ... ]`.
> 
> Perhaps it's a good idea to make it into something more sensible, like `[ { "repo_id": "123", "repo_path": "..." }, ... ]` or even `{ "123": { "repo_path": "..." }, ... }` while we are at it.

I am not sure why you think it is a weird data structure, I think expresses what we want it to be a "a list of repositories that should be mirrored". Each repository is represented by a number of key value pairs.

**Comment by ikapelyukhin** [comment]
> > It's a really weird data structure anyway: `[ { "123": { "repo_path": "..." } }, ... ]`.
> > Perhaps it's a good idea to make it into something more sensible, like `[ { "repo_id": "123", "repo_path": "..." }, ... ]` or even `{ "123": { "repo_path": "..." }, ... }` while we are at it.
> 
> I am not sure why you think it is a weird data structure, I think expresses what we want it to be a "a list of repositories that should be mirrored". Each repository is represented by a number of key value pairs.

Well, why wouldn't I think that. It's an array of hashes of hashes (and the middle hash has only one key). It requires two `for` loops to navigate. It should be either an array of hashes or just a plain hash.

**Comment by rjschwei** [comment]
> > > It's a really weird data structure anyway: `[ { "123": { "repo_path": "..." } }, ... ]`.
> > > Perhaps it's a good idea to make it into something more sensible, like `[ { "repo_id": "123", "repo_path": "..." }, ... ]` or even `{ "123": { "repo_path": "..." }, ... }` while we are at it.
> > 
> > 
> > I am not sure why you think it is a weird data structure, I think expresses what we want it to be a "a list of repositories that should be mirrored". Each repository is represented by a number of key value pairs.
> 
> Well, why wouldn't I think that. It's an array of hashes of hashes (and the middle hash has only one key). It requires two `for` loops to navigate. It should be either an array of hashes or just a plain hash.

But it is an "array" (aka "list" in Python") of hashes (aka "dict"ionary in Python). SOrry I am still confused about what you are after.

**Comment by ikapelyukhin** [comment]
> But it is an "array" (aka "list" in Python") of hashes (aka "dict"ionary in Python). SOrry I am still confused about what you are after.

It's a list of dicts of dicts, here's a JSON fragment:

```
[
  {
    "1632": {
      "description": "SLES12-Updates for sle-12-x86_64",
      "framework": null,
      "location": "/SUSE/Updates/SLE-SERVER/12/x86_64/update/"
    }
  },
  {
    "1633": {
      "description": "SLES12-Debuginfo-Updates for sle-12-x86_64",
      "framework": null,
      "location": "/SUSE/Updates/SLE-SERVER/12/x86_64/update_debug/"
    }
  },
  ...
]
```

Instead, it could have been just a dict of dicts (especially now that Python knows how to maintain dict key order):

```
{
 "1632": {
   "description": "SLES12-Updates for sle-12-x86_64",
   "framework": null,
   "location": "/SUSE/Updates/SLE-SERVER/12/x86_64/update/"
   },
 "1633": {
   "description": "SLES12-Debuginfo-Updates for sle-12-x86_64",
   "framework": null,
   "location": "/SUSE/Updates/SLE-SERVER/12/x86_64/update_debug/"
   },
  ...
}
```

Or it could have been an actual list of dicts:

```
[
 {
   "id": "1632",
   "description": "SLES12-Updates for sle-12-x86_64",
   "framework": null,
   "location": "/SUSE/Updates/SLE-SERVER/12/x86_64/update/"
 },
 {
   "id": "1633",
   "description": "SLES12-Debuginfo-Updates for sle-12-x86_64",
   "framework": null,
   "location": "/SUSE/Updates/SLE-SERVER/12/x86_64/update_debug/"
 },
 ...
]
```

Either one of those would simplify things, make parsing easier and most likely make n^2 for loops unnecessary.

**Comment by jesusbv** [comment]
> Either one of those would simplify things, make parsing easier and most likely make n^2 for loops unnecessary.

I agree that the n^2 loop is unnecessary for this case.

**Comment by rjschwei** [comment]
@jesusbv OK simplified to list of dicts, can you give this a quick once over? Thanks

**Review by ikapelyukhin — APPROVED** [review]

**Review by jesusbv — APPROVED** [review]
LGTM

**Pull request merged**
